---
title: "ERHS535 HW5"
author: "Eric Wendt"
date: "11/22/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.path = "graphs/", echo = TRUE,
                      warning = FALSE, error = FALSE, message = FALSE)
```

```{r}
library(magrittr)
```

```{r}
hom_data <- 
  readr::read_csv("../data/homicide-data.csv")
```

```{r}
# choose top homicide city
top_hom_city <- hom_data %>%
  dplyr::group_by(city) %>%
  dplyr::count() %>%
  dplyr::arrange(desc(n)) %>% 
  dplyr::ungroup()
```

```{r}
# cities with most homicides
top_hom_city %>%
  dplyr::slice(1:10)
```

```{r}
# homicides in New Orleans
no_hom <- hom_data %>% 
  dplyr::filter(city == "New Orleans") %>% 
  dplyr::mutate(unsolved =
                  disposition %in% c("Open/No arrest", "Closed without arrest"),
                unsolved_label = dplyr::if_else(unsolved == FALSE, "solved",
                                         "unsolved" ),
                victim_race_3 = forcats::fct_lump(victim_race, n = 3))
```

```{r}
# sf object
no_hom_sf <- sf::st_as_sf(no_hom, coords = c("lon", "lat"), crs = 4269)
```

```{r}
# Orleans Parish code: 22 071
no_blocks <- tigris::block_groups(state = 22, county = 071, cb = TRUE, class = "sf", progress_bar = FALSE)
```

```{r new_orleans_homicides, fig.height=6, fig.width=8}
no_hom_plot <- 
  ggplot2::ggplot() +
  ggplot2::geom_sf(data = no_blocks, color = "black") +
  ggplot2::geom_sf(data = no_hom_sf, ggplot2::aes(color = victim_race_3,
                                                  fill = victim_race_3))+
  ggplot2::facet_grid(.~ unsolved_label) +
  viridis::scale_fill_viridis(discrete = TRUE, name = "Victim Race") +
  viridis::scale_color_viridis(discrete = TRUE, name = "Victim Race") +
  ggplot2::labs(title = "Homicides in New Orleans", subtitle = "Parish County") +
  ggplot2::theme_bw()
no_hom_plot 
```

